### ISSUE TITLE
So.... uhm

### ISSUE THREAD

**Issue by IKnewOne** [NetroScript/Graveyard-Keeper-Savefile-Editor#11]
This happened
![image](https://user-images.githubusercontent.com/41551327/44848555-e9d94100-ac5f-11e8-8837-ec96a916fd54.png)
This save wasn't edited. I was editing another one, which i then deleted. This happened when i added 
either undefined(hop_seed) or undefined(hop_crop), tho i feel like it happened because of the seed. Looks like it shows the same thing throughout all saves.

**Comment by NetroScript** [comment]
Restart your game, by adding non existent items to the inventory you mess up the memory of your game. That's why the the warning was added about adding items in the notices. This is known behavior (I had it before too)

**Comment by NetroScript** [comment]
Also this is expected behavior and the 2 items you added exist in game. The thing is that you add them without a quality if you add them like that, and these items always have a quality, and a version without quality does not exist. If you would have set the quality to bronze / silver / gold before saving the save file, it would have worked without problems.

**Comment by NetroScript** [comment]
The best way for the user would be adding all items which have qualities in all their qualities so they can only change qualities of items which have them. The internal quality is decided by `:1`, `:2` and `:3` at the end of the name, where 1 - 3 is copper to gold. Currently you can also change the quality to a non existent item because I hoped people wouldn't try to get a gold quality stone f.e. (this is then a non existent item and will cause errors)
