### ISSUE TITLE
Blue tech points do not get edited

### ISSUE THREAD

**Issue by theAlevan** [NetroScript/Graveyard-Keeper-Savefile-Editor#24]
Hello.

I downloaded the latest release. Everything works except the blue tech points, which do not get edited.

**Comment by NetroScript** [comment]
Can you attach your save file so I can have a look at it?

**Comment by IKnewOne** [comment]
I had the same issue at some point in time. You can use blue scrolls and blue books for now

**Comment by NetroScript** [comment]
It could be you didn't have blue points before so you can't assign a value to them, I thought the way the scripts adds not existing values works, but maybe there is another value somewhere which determines if you are already able to use blue points

**Comment by theAlevan** [comment]
I uploaded the save. Inside the editor, I set the blue tech point count to 4, but in reality is past 1k thanks to the blue books.

[1.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2348417/1.zip)

Also, this save got corrupted somehow too, as I made a scrollshelf, filled it with items, like paper and ink, and now every storage is full with some nonexisting arm things (and of course I don't have backup, as I found this out later...).

**Comment by NetroScript** [comment]
I can tell you why this happens, I checked your save file and the list which contains information about these values has 2 entries for the blue points - I don't know if this happened because of my editor, but I doubt it because it only gets added when missing - and the thing is that my editor changes the last occurrence of the value, but it seems the game reads the first occurrence.
