### ISSUE TITLE
Using editor breaks inventory

### ISSUE THREAD

**Issue by Sandman1294** [NetroScript/Graveyard-Keeper-Savefile-Editor#26]
When you use the editor to add to your inventory it's breaks the inventory. When you go to move or use items the storage doesn't show up.

**Comment by NetroScript** [comment]
Which item(s) did you try to add? What was the last item in your inventory list. This sounds like a mistake in using the software, not a bug. Like it is said in the application itself editing the inventory can break the save file, because items you add might not exist, especially easy to do that mistake is when you change qualities without knowing if those qualities existed for that item. Another thing is that stack size is limited in some way and if you add an item like it is said in the description it copies the last item in the inventory and changes some values, meaning if the last item in your inventory is any specific item and you copy it, you can also cause memory errors when the game reads the save file.

**Comment by NetroScript** [comment]
It's not about sense, the game has a rather complex save structure and I don't have the time to create a perfect fail proof editor - like I said if you add new items it copies the last item in the current inventory, changes it's ID, amount, and repair value - meaning the editor works in most, if not all cases. The inventory can be corrupted by only 1 thing which occurred until now. And that is adding non existent items - which can happen by adding items in the wrong qualities. It could be possible that if the last item in your inventory has specific values (including a tool being equipped or a specific internal kind of script language (mostly in farming related items)) the game tries to load these, but for the category the item exists in they don't exist. But I can't really know that. Meaning if you want me to be able to do anything, I would need more information, like the last item in your inventory before adding new items, the amount, internal id and quality of the item you added.
