### ISSUE TITLE
Trying to add exhumation permission to a certain storage doesn't work

### ISSUE THREAD

**Issue by IKnewOne** [NetroScript/Graveyard-Keeper-Savefile-Editor#27]
Storage is '2' . Where the repair items  are

[2.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2352217/2.zip)

**Comment by NetroScript** [comment]
This is probably the last fix I will do for now, because I will be on vacation, feel free to continue reporting stuff while I am gone, I can also still merge requests. When I am back I will probably add support for modifying technologies (or at least take a look at how difficult it would be) and bump the version to the next number, because the bug from this issues prevents anyone on the compiled version to add items to storage units.
