### ISSUE TITLE
Chest/Trunk issue

### ISSUE THREAD

**Issue by no1scoot** [NetroScript/Graveyard-Keeper-Savefile-Editor#36]
After recent update 1.105 I noticed that when I change an item in my inventory, trunk or chest there is an issue. After I reload game It seems changes all the items in the other trunks, inventory or chest to match whatever was in the one I changed in the edditor. Also when I tried to add an item it wouldn't let me I could only change an existing item, but there was an issue if I changed an item to a burger the editor was ok but when I loaded the game it hadn't changed.

Hope that makes sense

**Comment by NetroScript** [comment]
Hey can you please upload your save?
I wanted to check if the update broke anything but I didn't / don't have the time to play myself so I couldn't test the new workers which are now additionally saved.
 
The behaviour you are having seems strange, because as far as I saw in the code changes of the game they didn't change code related to storage (because storage units are the main WGO objects with a filled inventory value) but of course I didn't check in depth.

And can you elaborate what you mean with you can't add an item? Like the question for me is if the problem is the front end code or the back end code. Like does the editor give you an error / does nothing happen in the editor / does the editor show everything correctly, but the game doesn't change?
And for me to reproduce it, do you still know which items you tried to add and did you change the item in your own inventory or another storage?

(About you not being able to change stuff there should be 3 possibilities which I have to look into:
1. You forgot to save it (I will just assume you didn't) 
2. When changing the item the visual part updates, but the data which is stored in the background doesn't 
3. The code changed something related to storage and it gets read and written incorrectly now)

**Comment by no1scoot** [comment]
I have been having a little play. I only get the error when trying to add item if I change the quality from default seems to be on all items. I can change the quality after I have added it and it seems fine. The storage trunks/inventory only corrupted after I added the burger also it doesn't show in the storage list but shows up in the editor. I have taken some screen shots. Which ever chest, trunk or inventory I add the burger to it changes all the others to show the same. I havnt tried any other food yet. I only noticed it cos I was doing the quest for the inquisitor.
[graveyard.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2554258/graveyard.zip)

**Comment by no1scoot** [comment]
oops didn't mean to close it.

**Comment by NetroScript** [comment]
Without having a deeper look at it but by expierence the thing with quality is known (like that can cause problems), but it could be a bug / mistake that the quality doesn't apply correctly when adding an item. And the burger could also either be a quality problem if it actually doesn't have a quality (f.e. the pink cake shows a gold quality in the game, but in reality has no quality in the item ID) or the ID which is saved for Burger in my editor is wrong

**Comment by NetroScript** [comment]
_(Generic Info): So I looked into it and the code itself has no problem, but the ID's are wrong, it says you can't add the burger because I have a list with all items which should have qualities so you don't create a item with a non existant quality. Burger isn't in that list as an item, so you can't add it because it doesn't exist. But you can add it without a quality (because then save wise it is a different item) and change the quality in the inventory, because it has less restrictions there because I hope people know what they are doing there._ 

So it is a mistake on my side to not include the burger IDs with qualities - but that is the smaller mistake of 2.
The main mistake here is my incorrect extracting of items. I have 2 items in my Editor which have the Localisation Burger, one of them is `burger` and one is `meal:burger` and only the meal one is an actual item (in it's 3 qualities) so I have to remove the `burger` entry and add the qualities and then everything should work as intended.

Thanks for finding this wrong item!

If you use the python version you can just redownload the repo in like half an hour, if you use the exectuable version you have to replace the `items.json` in the html folder when I commit the fix.
Or if you don't want to fix the editor itself, just add `meal:burger` to the inventory and then set its quality to gold.

And another thing, as far as it happened to me while creating the Editor, the fucked up inventories happen because of non existant items. The game tries to load the file and then loads non existant objects into the Memory, corrupting the memory of the game. So if you open a save file with a non existant item in one of the storage units you have to close and open the game again so the memory gets fixed.
