### ISSUE TITLE
JASONdecodererror??

### ISSUE THREAD

**Issue by christianleo333** [NetroScript/Graveyard-Keeper-Savefile-Editor#37]
![image](https://user-images.githubusercontent.com/45341487/48985076-4d122c80-f104-11e8-8a7b-e310f585e230.png)

**Comment by christianleo333** [comment]
what did i wrong??
Wrong Java or Python???
Have 64-bit installed both

**Comment by NetroScript** [comment]
Java is not used in the application, so that can't be the error.
It happens when the application tries to load your current save files. Can you give me all .info files in your savefile folder? Because one of them seems to have faulty JSON. 
If you don't want to do that you could also delete (or rename .info to .info.old) all .info files which don't have a corresponding .dat file.
Can your game load all the saves inside the save folder correctly?

**Comment by christianleo333** [comment]
Thank you
Make new saves delete the old ones

**Comment by NetroScript** [comment]
You probably don't need to delete the save, only at least 1 .info file seems faulty. The save data itself would be unaffected by that

**Comment by NetroScript** [comment]
A .info file should look like this:
![2018-11-26_12-08-09](https://user-images.githubusercontent.com/18115780/49010732-6d79cf80-f174-11e8-82b4-8a970634ac66.png)
(it contains basic data from which game version the file is, how many days you spent, when you last saved and what graveyard and church rating you have)

And at least 1 info file is probably faulty - meaning it doesn't have valid JSON Syntax (could be missing a character, or could have too much), that would look like this f.e.:
![2018-11-26_12-08-25](https://user-images.githubusercontent.com/18115780/49010747-74a0dd80-f174-11e8-85ec-bec10fd853af.png)
