### ISSUE TITLE
Item insert is bugged for me

### ISSUE THREAD

**Issue by lordfiSh** [NetroScript/Graveyard-Keeper-Savefile-Editor#39]
Items get over each other, after that you cant use/click them anymore ![2018-12-29 17_56_38-window](https://user-images.githubusercontent.com/389680/50540984-9f7bb880-0b9c-11e9-8fcd-ee631d1cdebd.png)

![2018-12-29 17_53_08-window](https://user-images.githubusercontent.com/389680/50540987-a1457c00-0b9c-11e9-86ff-2197c76a2fc6.png)

savegame:
[Graveyard Keeper.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2716609/Graveyard.Keeper.zip)

**Comment by NetroScript** [comment]
The sword and the axe you added are invalid item names so it corrupted the memory of the game - but that is an easy fix. Close your game, open the editor remove the 2 items in the inventory and add valid versions (	"axe_0", "axe_1", "axe_2", "axe_3" - "sword_0", "sword_1", "sword_damask", "sword_damask_gem", "sword_metal", "sword_metal_gem", "sword_steel", "sword_steel_gem") to the inventory and then start the game and it should work as intended. I am also adding that in the next update but because I am adding an additional small thing this still takes time. But you can also feel free to wait until I release 0.1.9.

**Comment by lordfiSh** [comment]
thanks 👍
