### ISSUE TITLE
I lose comfort of faith when i change things

### ISSUE THREAD

**Issue by MrX292** [NetroScript/Graveyard-Keeper-Savefile-Editor#4]
every time i change something the tech for comfort of faith isnt unlocked after
tried with money tech points and items

[save file.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2328308/save.file.zip)

**Comment by willrun4fun** [comment]
Same issue here.

**Comment by NetroScript** [comment]
This is quite interesting, and I have an idea why it is happening. When decoding the stored strings, I had the problem that "C" is encoded with 2 bytes, but everything else encoded with 1 byte, that is why I made a personal fix, changing it to C manually. Now it could be that when it encodes it again, it is encoded as ASCII, instead of Unicode, leading to this error. I will take a look at it when I have time again.

**Comment by NetroScript** [comment]
Before changing anything in the code, I took a look at the serialized words of my save which contained "C".
There only one seemed to be faulty `Clay, Circular saw, C4omfort of fait5, Corpses burning, @Clotho_merc5, @Clotho_merch_agai3, Clotho_va25, Clotho_po25, @Clotho_intenc8, @Clotho_be8, Clotho_need_hel29` C4omfort of fait5 instead of Comfort of faith. It seems only comfort of faith is wrong. I will also take a look at the serialized strings of your file. If the problem is only Comfort of faith, it might be enough to just fix that specific case.
