### ISSUE TITLE
Endless Notebook

### ISSUE THREAD

**Issue by Rutthless** [NetroScript/Graveyard-Keeper-Savefile-Editor#47]
Hey Jack_5515,
So I got the insufferable gamebreaking glitch that gets NPCs stuck and came across your savefile editor. Someone else said that this bug is related to sleep not triggering RelationGUI or something, so I thought I should just change the day using your editor to somehow force the NPCs to reset. Didnt work.
Astrologer shows up every day (actually never leaves). So I thought about adding the essential items to open the portal to my inventory related to the stuck NPCs (which are all that appear on specific days), but...
I cant find the Endless Notebook in your savefile editor. Typing "endless", "note", "notebook", "book", nothing works, it just isnt there. Can you please add it?
Also, some way to get the NPCs unstuck would be a gamefile saver, since the name of Lazy Bear Games apparently checks out because they are so lazy that they simply seem to not give a shit about fixing their broken game and havent even added the Town even though they promised it.
Anyways, great job mate! You did more for this game than the devs ever did.

**Comment by NetroScript** [comment]
I added the item, if you have check for updates enabled your game should offer to update it itself. 

About the stuck NPC's if I would know the cause, I could add a fix, but it never happened to me so I don't even have a save which I could inspect. Additionally currently I wouldn't have the time to extensively look into the save (parts which I didn't inspect for functionality of the editor) but I planned anyways to add some worker support at some point and should I ever get to it and the stuck NPC's still aren't fixed and I have multiple save files for comparing and debugging I could see if I can do something. But the bug could also be in the game files (which aren't saved) so the editor couldn't do much if that was the case.

But it is nice that now someone tried fixing them with the time function, so now you know that they don't trigger on their normal times.

If people want to inspect the problem themself I would assume the problem of the save would either be in (if you export a save file as JSON) savedata->game_logics (because you have f.e. bishop_spawn, which looks like this: 
![r0llksozrx](https://user-images.githubusercontent.com/18115780/51701177-2fcce200-2011-11e9-87f7-606060360a43.png)
but there only seem to be times, (but one could try resetting all of them and setting next execution to 1 seconds, or depending what the value means, I would need to look in the source code of the game
)
The only other idea I would have is modifying the world game object of the NPC, but I also don't know if they are just created by scripts at fitting times or f.e. exist the whole time (so you could edit them if they are not visible). This could also lead to problems, assuming you have 1 Entity of the Bishop, then using the editor you copy the one infront of your church from another save over using the editor, which causes 2 of them to exist, leading to bugs (maybe, didn't try it)
