### ISSUE TITLE
decoder.py - Invalid control character at line 74 column 182

### ISSUE THREAD

**Issue by jethrobebop** [NetroScript/Graveyard-Keeper-Savefile-Editor#48]
Can't run "Graveyard Keeper Savefile Editor.exe"

![image](https://user-images.githubusercontent.com/47224093/52076582-42a26200-258f-11e9-8c01-e00f1516929a.png)

1.011 (last release)
Windows version

Thanks for your work and in advance of replay

**Comment by jethrobebop** [comment]
FYI : Not happening in 0.1.10

**Comment by killerisajob** [comment]
The same thing happens to me

**Comment by NetroScript** [comment]
In that update I extracted the localisation of items from the game and applied them to the `locals.json` file - but problem happened there because the game names sometimes have tab as special character (\t) and in JSON it would be only valid is \t but it was the control code instead causing an error. I updated the `locals.json` file now and within like 5 minutes I also applied the fix to the windows version available for download so you can just redownload it and it should work (or you manually replace the `locals.json` in the data folder by downloading the new one in the repository).
Sorry that such a simple mistake happened (I normally also test the .exe, but didn't because the python version worked for me and I didn't change any "critical" code).

**Comment by NetroScript** [comment]
Updated the 0.1.11 release now

**Comment by jethrobebop** [comment]
working !
I applaude your reactivity and your professional conciousness.
Cheer !
J.
