### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Poeschl** [NetroScript/Graveyard-Keeper-Savefile-Editor#51]
**Describe the bug**
When a savefile is getting saved, a exception in the console appears and the savefile is not overwritten. The backup is in place.

The exception is:
```
Loaded file: C:/Users/Markus/AppData/LocalLow/Lazy Bear Games/Graveyard Keeper\1.dat
Traceback (most recent call last):
  File "S:\Programme\Python3.5\lib\site-packages\gevent\greenlet.py", line 536, in run
  File "S:\Programme\Python3.5\lib\site-packages\eel\__init__.py", line 190, in _process_message
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 223, in saveslot
KeyError: 'backupamount'
Thu May 30 20:25:07 2019 <Greenlet at 0x253562842a8: _process_message({'name': 'saveslot', 'call': 3.570741449204223, 'a, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with KeyError
```

**To Reproduce**

That is my savefile which caused the bug:

[save.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/3238264/save.zip)

1. Open the savefile
2. Save it
3. Error and nothing is saved

**Expected behavior**
Step 2 should overwrite the original savefile with changed settings if something is changed.

**Additional context**
I used the downloadable release 0.1.14 on windows 10

**Comment by NetroScript** [comment]
I just tried it out and found the problem, this happens when you use the application for the first time and the settings menu doesn't correctly save the amount of backups the user wants, if the application is restarted later there is a check in place which replaces this empty value by 2 - so it should work if you just open the application again. (Because then the settings file is already created and the back up value gets a default value of 2 if there is none)

**Comment by NetroScript** [comment]
Or to be exact the latest compiled release was published with the wrong settings menu which is missing the option for the amount of backups looking over it.

**Comment by NetroScript** [comment]
I now corrected the files contained in the .zip - But like I said before for you it should work by just restarting the application
