### ISSUE TITLE
[Bug] Delete Items on the floor

### ISSUE THREAD

**Issue by merlinx2k** [NetroScript/Graveyard-Keeper-Savefile-Editor#58]
I used delete Items on the floor.
Everything got deleted including the corpses lying on the floor, which is to be expected.

My problem is that the counter inside my morgue did not go down. so now i am at 6/6 corpses and the donkey would not bring new ones because i am at my limit, which i am not because i deleted the corpses.

I hope i explained the problem properly

**Comment by NetroScript** [comment]
Can you upload a zipped version of your save so I can have a look at it?

I can try to fix the problem in your specific save (or at least into it) and if it is a trivial fix either add it to the editor (that it will automatically do that) or add a warning there.

**Comment by NetroScript** [comment]
I would say the fix should be relatively doable without having a save to try it on.
The main inventory object (which is essentially the player object) has properties called `cur_bodies_count`, `in_morgue`, `body_min`, `body_max`, ... which I would assume store this count (because I looked through the morgue WGO's and they didn't have any reference to a body count) and changing them should fix your problem (for your save I can do that manually, for the later version I add it to the save editor) if that works well one might even be able to increase the max body count to no limit or a button to clear it, should it be bugged.

**Comment by merlinx2k** [comment]
i found that i had two corpses on a pellet so i was able to get new ones.
But never the less my bodies count is still off by 4.

here is my save file, hopefully you can fix it if not i guess i have to build more pallets :)
https://www.dropbox.com/s/dita1tp669p4hss/Graveyard%20Keeper.rar?dl=0

**Comment by NetroScript** [comment]
Just replace your 1.dat with the file from the zip (and well also don't forget to keep back ups).

I reset it to 0, test it out and tell me if everything is working as expected.

If everything is fine I will add it to the editor when I have more time. (Both that you can reset the value and that the clear drop automatically reduces the count of the morgue).

[1.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/3833603/1.zip)

**Comment by merlinx2k** [comment]
i played around for a while and it seems to be working fine.
thanks again for fixing my save :)
