### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by assassins7777** [NetroScript/Graveyard-Keeper-Savefile-Editor#59]
will be possible to add support for 32-bit operating systems

**Comment by NetroScript** [comment]
Which part of the base script is currently not supported on 32-bit systems?

**Comment by assassins7777** [comment]
I do not know exactly since I have windows 10 and all it tells me is that this program does not run on your PC to get another version for your PC talk to the publisher just tell me that and try compatibility trouble shooting does not detect or tell me the error.

**Comment by NetroScript** [comment]
Did you try this installation already:
![image](https://user-images.githubusercontent.com/18115780/71826442-388dbb00-309e-11ea-9e03-241fe631a2e7.png)
Or only the .exe release on the releases page?

**Comment by assassins7777** [comment]
I currently have Python, the version I currently have is the latest version of Python because I have programs that depend on it and I even have all the dependencies installed, I also don't know why I don't run the test on a Laptop with 64Bits operating system and it works no problem in my case the Laptop is Windows 10 32Bits and here is that it does not work for me I don't know why it is because as I said before I have Python Installed with Path enabled and I do not explain why it does not work if I have everything up to date.

**Comment by NetroScript** [comment]
> I do not know exactly since I have windows 10 and all it tells me is that this program does not run on your PC to get another version for your PC talk to the publisher just tell me that and try compatibility trouble shooting does not detect or tell me the error.

What you wrote there seems to me like you are using the `.exe` version, because python itself shouldn't give an error message like that (especially if it works for your other uses), so I am asking again (because I am still not sure) did you download [this](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/archive/0.1.18.zip) instead of [this](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/releases/download/0.1.18/Graveyard.Keeper.Savefile.Editor.-.Windows.-.0.1.18.zip)? 

The last link is a "frozen" state of my Python version with the modules, but my python version is the 64 bit version, which wouldn't work on a 32 bit PC, but the pure script (which is the source code) should work on 32 bit when executed with a 32 bit Interpreter.
If you are using the first link and not the `.exe` / windows zip could you supply me with the screenshot of the error code python gives you?

**Comment by assassins7777** [comment]
![Proof](https://user-images.githubusercontent.com/59509119/71866655-ca57f100-30bb-11ea-8a33-478b5bdedc1c.jpg)

I am currently using the exe version that is freez as you say but when opening it it does not give me code or anything just tells me what it shows in the photo nothing else does not give me an error of anything that I would like but does not give me any error is the first Once I have this issue with your program other times I had already used it and everything was fine.

**Comment by NetroScript** [comment]
Then again what I said above, the version you currently have won't work (like you realised) because it is a 64 bit .exe from my system. You said you use python yourself, meaning for 32 bit support the quickest solution would be downloading the [script release](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/archive/0.1.18.zip) and executing the main.py with python. (In the console `python main.py`)

**Comment by NetroScript** [comment]
This has been inactive quite some time, I will close it soon (in a few days) if no more conversation is made. If there are still questions / or a new similar problem and it  is already cloded feel free to reopen.

**Comment by NetroScript** [comment]
No further responses, so closing - if there are still problems considering this issue feel free to reopen
