### ISSUE TITLE
Tech points bug

### ISSUE THREAD

**Issue by aivarasx987** [NetroScript/Graveyard-Keeper-Savefile-Editor#6]
![screenshot_218](https://user-images.githubusercontent.com/42785429/44748570-ad4efd80-ab18-11e8-9d54-74bf739576a6.jpg)
Every time I try to change tech points this happens, why is that? Any ideas? (Screenshot after trying to load in-game, failing and then trying to use editor to fix the save, doesn't work, thanks for the auto backups ;D)

**Comment by NetroScript** [comment]
Did you set a language in the game which does not use the Latin writing system? (F.e. this text is written in the Latin system)

**Comment by NetroScript** [comment]
If that was the case, the problem would be that your game saves UTF-8 strings, but my script reads strings as ASCII, and for the few edge cases there are in the English localisation the strings are handled manually (or to be more exact, such an error happened with "C" when I started this project, and that's why strings where I know they contain "C" get specially handled) Because of the absence of more Unicode characters this handling was enough - if you have a different language, maybe upload the save file and I will see if I can implement Unicode handling.

**Comment by aivarasx987** [comment]
[1.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/2331078/1.zip)
Here is my save file, game language is English. Maybe it's my pc's language/region problem? Some time ago I was looking for encoding stuff, because I can't read some files, I see strange signs and stuff and it was Windows-1257 and Baltic at the end or something like that. Don't know if it's related to the problem. 
P.S. I'm from Lithuania which is a Baltic state(explains encoding)

**Comment by NetroScript** [comment]
I have no problem loading your save file, meaning it has to do with your encoding. Open the console in the folder of the Application, type `chcp 65001` in the console first (changing the code page to Unicode) and then execute the Application. If that fixes it, I maybe could try using win-unicode-console for the next update. Don't forget to add that command every time you want to open the editor, maybe a batch file would be useful.

**Comment by aivarasx987** [comment]
Either I did something wrong or It didn't work, oh well, no cheating for me I guess :D

**Comment by NetroScript** [comment]
Did your console say "Changed codepage to ..." or something similar? before you executed the application

**Comment by aivarasx987** [comment]
Yeah it did, save still gets corrupted after changing any of the tech points.
