### ISSUE TITLE
Bookshelves broke after edit 

### ISSUE THREAD

**Issue by Beskkov** [NetroScript/Graveyard-Keeper-Savefile-Editor#61]
So I topped of the inventory of the bookshelves under the church.  And everything broke. Now the game shows the "trunk" under my main inventory.

https://gyazo.com/52e127e91d4e9551c4da303d1ecf38fd

**Comment by NetroScript** [comment]
Can you send me your save before and after the edit? (The Editor makes backups of your save files, unless you disabled it).

Which changes did you do exactly?

The inventories breaking can happen when an item is added which doesn't exist, I am (/ was) pretty sure that the editor only contains the items which the game also has, but there could be one or some wrong ones included, that is why I ask what you added / changed.

But without being able to look at your save and seeing your changes I can't fix it right now.

To restore a backup unzip the most recent zip it created for your savefile, and rename that file to `<original name>.dat` - just to be save you should also not delete your current, broken `.dat`, but rename it to f.e. `<...>.dat.old`

**Comment by Beskkov** [comment]
Hi,
I didnt get a zip-file so I only have the current save file. 

[1.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/4270148/1.zip)

**Comment by NetroScript** [comment]
So I took a look at it, and you indeed added an item which doesn't exist (at least not for the game) - you added candles to the inventory and then set them to gold quality, but candle as item doesn't exist with qualities - I set it to candle_6 and will test it now to see if there is another mistake in the save. (But before testing I would already say that was the problem)

If there are no further mistakes I will post the slightly changed save here.

Additionally when looking at your save I saw some items weren't displaying correctly, so I will update it so brains and hearts and so on show and maybe also add a warning which tells you that you have a non existent item (or well an item which my editor doesn't know)

**Comment by NetroScript** [comment]
[1.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/4272201/1.zip)

This is the working save file.
Additionally to having a candle with qualities (which doesn't have it) you had notes, chapters and prayers without qualities when they needed them.

For the future I suggest using the autocomplete version, because then you can be sure everything works as intended. If you say you don't have automatic backups you might be on an older version of the editor (or check the settings if you have it disabled) - if you are on an older version I suggest updating for faster load times and less bugs.
