### ISSUE TITLE
Is there any way of reverting back to how a save was before i changed it?

### ISSUE THREAD

**Issue by WTheDumbass** [NetroScript/Graveyard-Keeper-Savefile-Editor#65]
So im a fuken dumbass and i played this game from day 85 to day 117 with edit app open from day 87 the whole time.

I then felt like getting 20 faith would be to time consuming so i went back to the edit app and added that not noticing that it was 32 days earlier from my curent save, then i made the change and came back and a huge part of my progress was gone. i freacked out and reaised that im dumb as fuck and then went to see if i can change it.

My question is if there is any way to get back to my old save, the save still says im on day 117 yet its day 87 when i check it ingame as well as in the edit app. i tried the backups bc i thoght they would be the backup of the save you had before the changes. but its just the same save but in a backup.

If there is a way to do that i missed then i do apoligise, if not then its no bigge just kinda sucks.

![Screen-7-2-2020_54900_PM](https://user-images.githubusercontent.com/67751427/86380579-8883be00-bc8c-11ea-816f-f292441ff426.png)

![Screen-7-2-2020_55105_PM](https://user-images.githubusercontent.com/67751427/86380664-a6512300-bc8c-11ea-9f7e-720e9f420a6b.png)

The bottom one is the one im talking about.

Anyways hope alls well during these times ´:)

**Comment by NetroScript** [comment]
Assuming you saved your game before doing the edit (because you can't do live edits with this anyways) and you kept the default backup settings there should be a backup file.

The one you are looking for is `<your savefile>.dat.back_1.zip` - this should always be the most recent one. On save with the editor, it rotates the previous backups by one and then zips your current .dat file, deletes the old .dat and creates a new one with the updated information.

If that backup file does not work (remember don't use the `.dat.backup.n` as those are the backups from the game and not the editor) your progress is sadly lost. But like I said, in theory with default settings there should be a backup file (when you saved your game before the edit).

**Comment by WTheDumbass** [comment]
thank you so much for responding and helping!

I got it to work! i found the right save and i looked it over and it was just as o left it before going full dumbass. 

Question, how do i override or othervise make this save the active one? i only seem to be able to export the saves into .dat or .json files 
![Screen-7-5-2020_70437_PM](https://user-images.githubusercontent.com/67751427/86537856-67bca200-bef2-11ea-878b-dbd5a21f053a.png)

This is from the one im trying to save.

![Screen-7-5-2020_70608_PM](https://user-images.githubusercontent.com/67751427/86537887-96d31380-bef2-11ea-9644-a342cb04a8f0.png)

This is from the one i fucked up on.

i might just have missed it but i read the read me file as well and couldnt find it. i do apoligize for asking so much.

apoligies as well for taking so long to respond i went on a trip.

**Comment by NetroScript** [comment]
You don't need to load the save up again in the editor.

Rename the save which you overwrote by mistake (I will assume now that it is slot 2 and will continue to use 2) from `2.dat` to `2.dat.old` in your folder, so that you still have it.

Then unzip your `2.dat.back_1.zip` and unpack the `2.dat.back_1`. Then just remove the `.back_1` leaving you with `2.dat`. If you now load the save file, it will load 2.dat which is your previous save.

**Comment by WTheDumbass** [comment]
Yes that worked! thank you so much i apritiate all the help!

Really love the editor, amazing work!

Hope all is well!
