### ISSUE TITLE
[BUG] Unable to load save

### ISSUE THREAD

**Issue by krisavi** [NetroScript/Graveyard-Keeper-Savefile-Editor#66]
**Describe the bug**
When trying to load a save I get
```
Extracting String Array
Error:
Traceback (most recent call last):
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 151, in getsavefile
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 19, in decode
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 193, in extractserializer
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 216, in extractstring
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\tools.py", line 28, in read
struct.error: unpack requires a bytes object of length 1
```

**To Reproduce**
Trying to load a save.

**Expected behavior**
Save is loaded

**Please also add the following Information:**
* Version Latest 0.1.19
* Using windows version

**Additional context**
May be something to do with game update and the new DLC release.

**Comment by faragher** [comment]
Save format has changed. The initial release of the DLC worked, but the first patch changed everything.

**Comment by NetroScript** [comment]
> Save format has changed. The initial release of the DLC worked, but the first patch changed everything.

I do not own the DLC, but I compared the base game version 1.303 with 1.206 and as far as I can see with a short overview loading and saving remained the same.

___________________________________________

@krisavi Can you upload the save file which doesn't work?

I will take a look at it and see if something is broken (and if the editor doesn't work with the DLC anymore).

Also should I buy the DLC for myself, I will also add the new / updated localization and the new items.

**Comment by faragher** [comment]
> > Save format has changed. The initial release of the DLC worked, but the first patch changed everything.
> 
> I do not own the DLC, but I compared the base game version 1.303 with 1.206 and as far as I can see with a short overview loading and saving remained the same.

I'd be happy to be proven wrong. 

Anyway, I know I wasn't the one asked, but since I have nearly identical issues:

```Extracting String Array
Error:
Traceback (most recent call last):
  File "main.py", line 151, in getsavefile
    data = decoder.decode(curpath)
  File "/home/faragher/Graveyard-Keeper-Savefile-Editor/data/decode.py", line 19, in decode
    sd = self.extractserializer(b)
  File "/home/faragher/Graveyard-Keeper-Savefile-Editor/data/decode.py", line 193, in extractserializer
    data.append(self.extractstring(stream, True))
  File "/home/faragher/Graveyard-Keeper-Savefile-Editor/data/decode.py", line 216, in extractstring
    buffer.append(stream.read("int8"))
  File "/home/faragher/Graveyard-Keeper-Savefile-Editor/data/tools.py", line 28, in read
    return struct.unpack(form, val)[0]
struct.error: unpack requires a buffer of 1 bytes
```


here is a save file with the issue.

[save.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/5476018/save.zip)

**Comment by NetroScript** [comment]
> I'd be happy to be proven wrong.
> 
> Anyway, I know I wasn't the one asked, but since I have nearly identical issues:
> 

Heh I am happy to tell you that I can prove you wrong @faragher, and the problem with your save will most likely be the same as the problem from @krisavi.

For those interested in the source of the error, here a tiny bit of detail.
When saving, the game also saves a list of strings at the end of the save file. Now normally they are saved the following way: `<Length of String><Char 1><Char 2>...<Char N>` and this save editor just loads that. Now the thing is, the save format sometimes has strings which are saved as the length of for example 25 but actually have the length of 26, which totally throws my save editor off. The assumption always was that this was more or less random and coincidences, but doesn't seem like it. We now had the repeated case of the letter `C` being saved wrong. 
In this specific case a string with the length 25 is saved, the byte buffer the editor reads would be `[14, 12, 109, 29, 50, 6, 4, 25, 14, 5, 8, 3, 50, -47, -127, 5, 8, 8, 30, 8, 50, 29, 12, 25, 25]` - you can already see negative bytes there which make no sense (in the string encoding) - because those negative numbers occur, we know we need to read an additional byte, meaning we have `[14, 12, 109, 29, 50, 6, 4, 25, 14, 5, 8, 3, 50, -47, -127, 5, 8, 8, 30, 8, 50, 29, 12, 25, 25, 20]`, but internally we still need to remember the length 25 (despite it being 1 byte longer). Now if we decode their encryption and turn that into a string we get `camp_kitchen_Dheese_patty` - the correct value would be `camp_kitchen_Cheese_patty` so once again capital C in the string is the error. 
And these wrong saved bytes (I have no idea how the game correctly loads it, because it more or less has exactly the same algorithm) caused the save editor to be offset by 1 byte when reading. (Which leads to those errors)

**Comment by NetroScript** [comment]
This will be in the next release, but if you want to use the editor for now, you have to use the python version.
I also want to include #67 in the next release (if it is feasible) and like I said before I might also buy the DLC for myself, if so I will include the new item names and images.
So the .exe file might take a few days (to weeks) more.

**Comment by faragher** [comment]
Awesome. Glad to be proven wrong. Also, nice catch and thanks.
