### ISSUE TITLE
[Suggestion] Fix for NPCs stuck in the Church

### ISSUE THREAD

**Issue by hella-steve** [NetroScript/Graveyard-Keeper-Savefile-Editor#67]
When conducting a sermon as usual, sometimes there will be one or more NPC followers stuck in the church that do not disappear. After a certain number of days, the sprite will change from the default hooded follower to a generic "farmer" sprite, and remain there, seemingly for all eternity.

Uploading save file for you to have a look at.

[NPC Stuck Save.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/5484859/NPC.Stuck.Save.zip)

**Comment by NetroScript** [comment]
Hey @hella-steve , I also added the new items by now and took a look at your save.
I removed the sole `npc_church_visitor` entity.
Sadly I can't load the save file myself, because I don't have the new DLC, so can you try loading it in and tell me if everything is fixed (If so I will add it as a 1 click button to the save editor).

If this doesn't fix it, I might need to get the DLC for myself to have some visual feedback (to see the changes also in the game).

Also where do the farmer sprites appear? Do you currently have multiple NPCs in the church or just a visitor NPC.

Here the "fixed" save:
[removed_church_visitor.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/5506986/removed_church_visitor.zip)

(Just save your old `1.dat` as for example `1.dat.backup` and place `removed_church_visitor.dat` there after renaming it to `1.dat`)

**Comment by hella-steve** [comment]
Hey @NetroScript,

That successfully removed the sprite from the church! Usually they seem to get stuck at the outside of the church benches, preventing the player from moving through the aisles. I only had one NPC stuck in my game, but have seen screenshots of 2 or more that remain in the church.

Thanks a lot!
