### ISSUE TITLE
[UPDATE] New Items

### ISSUE THREAD

**Issue by thelapisfox** [NetroScript/Graveyard-Keeper-Savefile-Editor#69]
**Describe the bug**
Set all grave decorations to max does not work right in new Game of Crones DLC. This is because new grave decorations have been added and the highest of these are;

Marble Grave Fence V (Add 7 to the grave);  grave_bot_mrb_5
Marble Sculpture IV (Add 9 the to grave);  grave_top_highangel_mrb_1

While the editor does show the in-coding name of the new items, it only shows 'undefined' with a grey ? for the icon on all GoC items. This also prevents one from adding any of these items as they are not included in the dropdown lists.

**To Reproduce**

Make sure you have Game of Crones DLC, complete the camp and purchase all recipes from the Gravedigger refugee and learn them. Save and load into Save Editor. Notice all new items are undefined. Click on 'Set all grave decorations to the highest'. Save and go into game to see no change.

**Expected behavior**
Expect all grave spots to be upgraded to the new decorations listed above.

**Please also add the following Information:**
* Used version of the save game editor: 0.1.19
* If you are using the Windows version or the python version: Python version using the python from Windows Store.
* If you have a problem in the editor without anything being shown in the python console, please add your version of Chrome: Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by NetroScript** [comment]
Hey, the update 0.1.20 added the new items, I also changed the item IDs to the ones you supplied. Can you test again if the button now works correctly for the DLC?

If so I will (when I have time) change it so that you can set your game version somewhere and then use that button. (And depending on your version it will use the different items)

As of right now (because I didn't think about it) it only does the new items, but that doesn't work for older versions of the game. Is what I think, but it might be worth trying out without DLCs too, because the items are also contained within the base game.

**Comment by thelapisfox** [comment]
Can confirm that all graves are now at 16 with correct grave decorations and new DLC items are no longer undefined; however, under additional inventories, you missed the camp storage, which, from testing, appears to be refugee_camp_depot (adding this to the storage list of items.json allows the editor to show it).

**Comment by NetroScript** [comment]
I also checked just now, the newer decoration versions do not work in the older game version.

**Comment by NetroScript** [comment]
BTW I also want to thank you for supplying the information for the DLC items and camp storage. 
Because I don't own the DLC I couldn't have added them myself. (And I also wouldn't have seen that it doesn't work).
