### ISSUE TITLE
Need update for the new DLC

### ISSUE THREAD

**Issue by Kiwibomber** [NetroScript/Graveyard-Keeper-Savefile-Editor#75]
Please make a Update for the new dlc
eg Zombies can up to 65 % / 26 white skulls.

Thanks.

**Comment by NetroScript** [comment]
I updated the editor now to have the icons and ids for the Better Save Soul DLC.

Generally speaking I would also add a 65% worker button instead of the current 40% one. The problem there is, that I don't play the game anymore myself, so I can't create a save with a reference worker.

If any of you have a save file with a perfect worker, feel free to upload the save here, and I will update the application to support 65% workers, if you have the latest DLC.

**Comment by DeadElle** [comment]
Here's the save, tnx for your efforts on still keepin' up the project!
[1.zip](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/files/7532168/1.zip)

**Comment by Kiwibomber** [comment]
Thanks @DeadElle for the file. I wouldn't have gotten around to making the file until now.

**Comment by NetroScript** [comment]
Oh no, while digging around in the code (to determine if the 65% worker zombies would work in a non Save Soul DLC game (spoiler: they don't) I discovered something very interesting:

![Graveyard_Keeper_s48pFUocQz](https://user-images.githubusercontent.com/18115780/141664119-36493972-c01d-4433-8e5f-5a1b3323039e.png)

Now I am not sure if I should make a 100% button (because that would also work for non DLC owners), or just implement the original 65% for DLC users, which falls back to the 40%, if the DLC is not installed.

Or even make a input field where the user can choose himself how much % his workers should have (although that would require some additional work)

So because you requested the feature, what is your opinion on it?

@Kiwibomber 
@DeadElle

**Comment by Kiwibomber** [comment]
wow, cool. 
OK, my personal target is 26 white skulls eq 65%. (1 ws = 2,5%)
but if you can use a slider (https://www.w3schools.com/howto/howto_js_rangeslider.asp) , a display with the number of white skulls or percent would be nice.
And then you can also just go up to the maximun value.
maybe with hints where to which dlc goes or so.

By the way I am thinking how to get the value (290% / 116 white skulls) in the game. 😄 Ideas?

**Comment by Kiwibomber** [comment]
Oh one more question about the savegame: can you find out why you still have an open task with Marquis Teodoro Jr? The problem is not answered on Steam. The NPS usually has 90 or 100 points and still one task.

Thanks.

**Comment by DeadElle** [comment]
> So because you requested the feature, what is your opinion on it?

Personally, I would choose the 65% as it's the maximum intended reach, but, as long as we're here, I believe putting a field with the custom min/max % would be the feature that satisfies everyone.

That said, I had a look into your code and the save by myself, and I see why that requires some work; maybe just limiting to a drop-down menu with the 40/65/100% would be enough and not that much hassle. ;)

**Comment by fachriem** [comment]
please make it happen :) i really hope for the 100% efficiency..

**Comment by NetroScript** [comment]
> Oh one more question about the savegame: can you find out why you still have an open task with Marquis Teodoro Jr? The problem is not answered on Steam. The NPS usually has 90 or 100 points and still one task.
> 
> Thanks.

Sorry I can't help you with that (at least not with an unreasonable amount of work) - quest data is stored outside the code in data files, so there is no easy way for me to view possible quest lines.

But generally speaking the points are arbitrary numbers, meaning each quest adds a different amount of them to the relationship. And they designed the quests in a way which mostly result in the number of 100 points.

**Comment by Kiwibomber** [comment]
![Anmerkung 2021-11-14 182852](https://user-images.githubusercontent.com/18040502/141691650-10528527-d503-4603-b50d-8a9ce951c0e9.jpg)

The bodies in the graves need a update too ;)

**Comment by NetroScript** [comment]
How many skulls is the maximum currently? 26 there too?

**Comment by Kiwibomber** [comment]
at the moment is 26 skulls the maximun value. see the picture (11 + 15 ).
but maybe can u make more dymanic, so like the worker value ?!

**Comment by NetroScript** [comment]
I can make it adjustable like the worker value, but the problem with that is the bodies losing all the body parts besides the brain. I don't know if people ever would want to have the original body parts at some point.

**Comment by Kiwibomber** [comment]
I don't think anyone is taking the bodies back out of the graves. And besides, it would be a bit more future-proof.

**Comment by NetroScript** [comment]
I added it in ba73c840529f7fe8954cfbe0c51e85ff2996cbbd now.

The .exe is the same release download as before (I replaced the build of 0.1.24). I added the note to the release entry.

**Comment by Kiwibomber** [comment]
![grafik](https://user-images.githubusercontent.com/18040502/141731998-0b3a3d12-074c-4487-88b6-ef7edf37f8a6.png)

alle graves looks like so. 
what to do?

**Comment by Kiwibomber** [comment]
No work needed. 
i simply added the 7 to the 26 and thus i had 26 white skulls in the graveyard.

**Comment by NetroScript** [comment]
I am sorry for that, I was so lazy and just used the same body I had for the worker, and forgot, that workers could have red skulls.
I fixed it in another quick update so you have to redownload the file.

Also discussed here: #77.

You can either replace the data.json file as described in that comment: https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/issues/77#issuecomment-968767721 or you redownload the entire thing again.
