### ISSUE TITLE
[BUG] Cant Load Save Games

### ISSUE THREAD

**Issue by Kobra299** [NetroScript/Graveyard-Keeper-Savefile-Editor#78]
**Describe the bug**
I just run the Graveyard Keeper Savefile Editor.exe and the console displays this info 
seems to be looking for python in different location to system info

Looking for save files in the folder: C:\Users\User\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper
Traceback (most recent call last):
  File "S:\Programme\Python3.5\lib\site-packages\gevent\greenlet.py", line 536, in run
  File "S:\Programme\Python3.5\lib\site-packages\eel\__init__.py", line 190, in _process_message
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 143, in get_savefiles
IndexError: list index out of range
Tue Nov 16 23:30:25 2021 <Greenlet at 0x1bb72c9f898: _process_message({'name': 'get_savefiles', 'args': [], 'call': 2.08, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with IndexError

**To Reproduce**
run newest version of the Graveyard Keeper exe

**Expected behavior**
I expected it to load the save files

**Screenshots**

**Please also add the following Information:**
* Used version of the save game editor
Graveyard.Keeper.Savefile.Editor.-.Windows.-.0.1.24

* If you are using the Windows version or the python version
Windows 10 and Python Verson 3.8.5
* If you have a problem in the editor without anything being shown in the python console, please add your version of Chrome

**Additional context**

**Comment by NetroScript** [comment]
The python is shown on a different path, because it is the path from my PC, this is due to it being frozen, the windows .exe doesn't use the python you have installed on your PC.

The error you get is because of a malformed `.info` file (although it would also be my responsibility to parse it a bit better).

How many `.info` files do you have in your saves folder (in `C:\Users\User\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper`)?

If you want (and there aren't too many) you can upload all of them (just the small `.info` files) and I can check which one is causing the problem.

Speaking broadly, my editor extracts the graveyard rating and the church rating, and some files don't have that saved, this then causes errors because of invalid array accesses.

**Comment by NetroScript** [comment]
Ok, you don't even need to do anything, if you download the same release again, it should work now, I improved the loading of the `.info` files so that your problem shouldn't happen anymore. 

See commit 6fdc54d7c1a0cb7c668bf18b4e40e9ec7c8141d6 for reference.
