### ISSUE TITLE
Feature request: possibility to skip quest or mark it as complete in any way

### ISSUE THREAD

**Issue by portfolis** [NetroScript/Graveyard-Keeper-Savefile-Editor#85]
Hi! Is it feasible to add possibility to skip quest in the game? In any way:

 - Just mark it as complete
 - Or unlock dialog option which normally is available only when some conditions are met
 - Any other ideas?

**Comment by NetroScript** [comment]
Sorry for the long radio silence, this is due to me being quite busy.

In theory this would be possible, but it is probably too complex to implement in a save editor.
Internally the game uses several systems for quests (NPC tasks, quests themselves, and for example what is in the save phrases for progress), and they are mainly driven by a visual scripting language they are using (or I would guess it is). 
As this isn't information accessible, and interconnected this isn't something really feasible. At least not with the overview I have over the system.

**Comment by ihor-drachuk** [comment]
Understand. Anyway, thank you for your answer!

**Comment by portfolis** [comment]
Understand. Anyway, thank you for your answer!
