### ISSUE TITLE
Items not available to create with this

### ISSUE THREAD

**Issue by IKnewOne** [NetroScript/Graveyard-Keeper-Savefile-Editor#9]
So far i found that wooden planks and fake coins for mrs. Charms quest are uncreatable in this app. Is there a good way to list you such items in the future, not using issue option ?

**Comment by NetroScript** [comment]
If you want to add items, you can also make a pull request. [This file ](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/blob/master/data/html/items.json) contains a list with the items accepted as input in the editor. It uses the internal names, so if you are unsure which item has which internal name, try taking a look at [this](https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/blob/master/data/locals.json) (just search for the item name). Although you have to watch out, because that file still has some errors, but they should be obvious by name. (F.e. "coal": "Clay" was a mistake before, but you should be able to see what the internal name is). Do you want to add those 2 items yourself or should I do it? Considering item images which are not yet on the wiki, I will add them later, wooden_planks is already as correct image available. Generally it seems a lot of quest items were missing, because those were not on the wiki page where I extracted items.

**Comment by IKnewOne** [comment]
Okay then. But dont i have to be 'invited' on github to make pulls? I was once using github desktop and i dont really know how exactly to work with it.
I think i'll add them sometime later. Maybe with some more items along the way.

**Comment by NetroScript** [comment]
You can also add the images if you find them, but it might be that the wiki doesn't have them. Considering for names being double - it is more or less intentional. I tried to extract the localisation file from the game files. But I didn't manage to extract them automatically, so I did it semi automatically which lead to some errors being in them (most likely) - but they contained different internal names for the same thing, and because I don't know which one is used when in the game I left them in, because better to have more, than having one not working. F.e. some organs contain information about the skulls they affected.

**Comment by IKnewOne** [comment]
Making item selection something like -choose category - choose item would be cool, but i guess thats a lot of work to do. I'll look in ~ 10 hours into it and understand how images are stored in this editor to help you in your doings :^)

**Comment by NetroScript** [comment]
The images are just in the /data/html/rsc folder with <internal name>.png as name. Item categories could be added easily, at least in the way that the application knows which one is which. (You would need to make separate lists of items, or add attributes to them). The question would be how to present that to the user, considering I use a ready made autocomplete option, which would need to be replaced. And currently I don't think I have the time to add a feature like this which doesn't change the usability (Like I think starting to type any part of the item name is already a good implementation so the user doesn't need to know internal ID's). I could also make it possible for the user to select any possible localisation. But the problem there would be a) a huge list and b) users could break their save file because they don't know what they are doing (that is why it is restricted to a specific list).

**Comment by IKnewOne** [comment]
For example, i i see beer.png and there is cup_beer internal name. How do i bind them ?

**Comment by NetroScript** [comment]
You don't bind them at all, you will see there also is a `cup_beer.png`, it will use that as an image, beer.png is from [this](https://i.imgur.com/TRW3426.png).

**Comment by NetroScript** [comment]
To add an item to the Editor, you would just need to add a `"<item name>",` to the list in `items.json`. It would already work then. If there is no translation for it, it would show "undefined" and if there is no image for it, it would show the image of a question mark.

**Comment by IKnewOne** [comment]
Ok, thanks for your time

**Comment by IKnewOne** [comment]
I added a line "quest_fake_coins", in my items.json, but when i try to add the item, it says it doesn't exist. What am i doing wrong?

**Comment by IKnewOne** [comment]
In case you will look at this issue: i understood the problem. "quest_fake_coins" was changed into 'coins'
