### ISSUE TITLE
[BUG] menu popup not scaling

### ISSUE THREAD

**Issue by mRichard629** [NetroScript/Graveyard-Keeper-Savefile-Editor#93]
**Describe the bug**
launch save editor click add item
when the menu pops up it looks like the screenshot

it should scale with screen resolution and DPI but it doesnt. I tried it on 3 separate screens. 1440p monitor, 1080p tv and 1080p handheld device *asus rog ally* all 3 had the same issue

using the most recent windows version as of posting of this report
![Screenshot of issue on 1440p monitor](https://github.com/user-attachments/assets/09569fab-2e5f-4bca-ab2b-dd8e02b2c415)

**Comment by NetroScript** [comment]
This is fixed in 82c88da, however the change is so minor, that I don't think the application needs a new version for that. If you use the Python version you can just do a git pull. Maybe I will update the already uploaded zip files with just the changed CSS file. (You can also update your local copy by just replacing the `html/css/main.css` with the updated file)
